networks:
  simon_network:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    container_name: simon_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${APP_CODE_PATH_HOST}:/var/www/html
    depends_on:
      - php
    networks:
      - simon_network

  php:
    build:
      context: ./php
      args:
        PHP_VERSION: ${PHP_VERSION}
        USE_CHINA_MIRROR: ${USE_CHINA_MIRROR}
    container_name: simon_php
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www/html
    environment:
      - PHP_VERSION=${PHP_VERSION}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - redis
      - mysql
    networks:
      - simon_network

  mysql:
    build:
      context: ./mysql
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
    container_name: simon_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - simon_network

  redis:
    build:
      context: ./redis
    container_name: simon_redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/logs:/var/log/redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - simon_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: simon_phpmyadmin
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - simon_network

  workspace:
    image: php:${PHP_VERSION}-cli
    container_name: simon_workspace
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www/html
    working_dir: /var/www/html
    networks:
      - simon_network
    tty: true
    stdin_open: true
    depends_on:
      - php
      - mysql
      - redis